default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  primary:
    <<: *default
    database: stock_selector_development

  queue:
    <<: *default
    database: stock_selector_development
  
  cable:
    <<: *default
    database: stock_selector_development

test:
  primary:
    <<: *default
    database: stock_selector_test

  queue:
    <<: *default
    database: stock_selector_test
  
  cable:
    <<: *default
    database: stock_selector_test

production:
  primary:
    <<: *default
    database: stock_selector

  cable:
    <<: *default
    database: stock_selector_cache

  queue:
    <<: *default
    database: stock_selector